### ISSUE TITLE
Exception has found after migration. 

### ISSUE THREAD

**Issue by pil78** [alexreinert/ARSoft.Tools.Net#31]
Hi,
during usage of you library sometimes we track the exception:
`System.Exception: Error parsing dns query
       ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
         at System.ArraySegment`1.System.Collections.Generic.IList<T>.get_Item(Int32 index)
         at ARSoft.Tools.Net.Dns.DnsMessageBase.ParseDomainName(IList`1 resultData, Int32 currentPosition, Int32& uncompressedLabelBytes)
         at ARSoft.Tools.Net.Dns.DnsQuestion.Parse(IList`1 data, Int32& currentPosition)
         at ARSoft.Tools.Net.Dns.DnsMessageBase.ParseQuestionSection(IList`1 data, Int32& currentPosition, Int32 recordCount)
         at ARSoft.Tools.Net.Dns.DnsMessageBase.ParseInternal(IList`1 data, SelectTsigKey tsigKeySelector, Byte[] originalMac)
         at ARSoft.Tools.Net.Dns.DnsMessageBase.CreateByFlag(IList`1 package, SelectTsigKey tsigKeySelector, Byte[] originalMac)
         at ARSoft.Tools.Net.Dns.DnsServer.ProcessRawPackageAsync(IServerConnection connection, DnsReceivedRawPackage queryPackage, CancellationToken token)
         --- End of inner exception stack trace ---
         at ARSoft.Tools.Net.Dns.DnsServer.ProcessRawPackageAsync(IServerConnection connection, DnsReceivedRawPackage queryPackage, CancellationToken token)`

Our dev-ops engineer managed to reproduce this with small powershell sceipt:
`function Send-UdpDatagram
{
      Param ([string] $EndPoint, 
      [int] $Port, 
      [string] $Message)

      $IP = [System.Net.Dns]::GetHostAddresses($EndPoint) 
      $Address = [System.Net.IPAddress]::Parse($IP) 
      $EndPoints = New-Object System.Net.IPEndPoint($Address, $Port) 
      $Socket = New-Object System.Net.Sockets.UDPClient 
      $EncodedText = [Text.Encoding]::ASCII.GetBytes($Message) 
      $SendMessage = $Socket.Send($EncodedText, 12, $EndPoints)
      $Socket.Close() 
} 

While ($True){
    Write-Host "Send Message"
    Send-UdpDatagram -EndPoint "127.0.0.1" -Port 53 -Message "F/*/**966jgFF"
}`
Could you please check this and fix, because I have no ways to override or implement this by myself.

**Comment by pil78** [comment]
PS: This has started after migration our application from 2.x.x to 3.x.x version. (We changed our code from old .net framework to .net 6)

**Comment by pil78** [comment]
Thanks for answering. 
Yep, I handled the error and ignoring - what I did for now.
